protected/models/CdrStatus.php
<?php

/**
 * This is the model class for table "cdrstatus".
 *
 * The followings are the available columns in table 'cdrstatus':
 * @property integer $id
 * @property integer $is_processed
 * @property string $process_time
 * @property integer $process_cnt
 */
class CdrStatus extends CActiveRecord
{
    static $ftpConn = null;
    public static function batchArchive($fromId,$toId)
    {
        $c = new CDbCriteria();
        $c->addBetweenCondition('id',$fromId,$toId);
        $batchList = CdrStatus::model()->findAll($c);
        foreach ($batchList as $row)
            $row->uploadArchive(false);

    }
    public static function connectFtp()
    {
        if (!empty(CdrStatus::$ftpConn)) return CdrStatus::$ftpConn;
        $conn_id=ftp_connect(Yii::app()->params['archiveHost']);
		$login = ftp_login($conn_id,Yii::app()->params['archiveUser'],Yii::app()->params['archivePwd']);
        if (!$login) throw new CHttpException(500,"Unable to login to Archive server");
        ftp_pasv($conn_id,TRUE);
        CdrStatus::$ftpConn = $conn_id;
        return $conn_id;
    }
    public function getArchiveSize()
    {
        $prefix1 = '/a2pdata/pbxbill/CDR/DONE/';
        $prefix2 = '/a2pdata/pbxbill/CDR/DONE2015/';
        $prefix3 = '/a2pdata/pbxbill/CDR/DONE2016/';
		$prefix4 = '/a2pdata/pbxbill/CDR/DONE2017/';
		$prefix5 = '/a2pdata/pbxbill/CDR/DONE2018/';
		$prefix6 = '/a2pdata/pbxbill/CDR/DONE2019/';
        $fname = 'HKVCDR.'.$this->id;
        $conn = CdrStatus::connectFtp();
        $n = 0;
        $n = @ftp_size($conn,$prefix1.$fname);
        if ($n>0) return $n;
        $n = @ftp_size($conn,$prefix2.$fname);
        if ($n>0) return $n;
        $n = @ftp_size($conn,$prefix3.$fname);
        if ($n>0) return $n;
        $n = @ftp_size($conn,$prefix4.$fname);
		if ($n>0) return $n;
		$n = @ftp_size($conn,$prefix5.$fname);
		if ($n>0) return $n;
		$n = @ftp_size($conn,$prefix6.$fname);
        if ($n>0) return $prefix6.$fname;
        
        return 0;
    }
    public function getArchiveName()
    {
        $prefix1 = '/a2pdata/pbxbill/CDR/DONE/';
        $prefix2 = '/a2pdata/pbxbill/CDR/DONE2015/';
        $prefix3 = '/a2pdata/pbxbill/CDR/DONE2016/';
        $prefix4 = '/a2pdata/pbxbill/CDR/DONE2017/';
        $prefix5 = '/a2pdata/pbxbill/CDR/DONE2018/';
        $prefix6 = '/a2pdata/pbxbill/CDR/DONE2019/';
        $fname = 'HKVCDR.'.$this->id;
        $conn = CdrStatus::connectFtp();
        $n = 0;
        $n = @ftp_size($conn,$prefix1.$fname);
        if ($n>0) return $prefix1.$fname;
        $n = @ftp_size($conn,$prefix2.$fname);
        if ($n>0) return $prefix2.$fname;
        $n = @ftp_size($conn,$prefix3.$fname);
        if ($n>0) return $prefix3.$fname;
        $n = @ftp_size($conn,$prefix4.$fname);
		if ($n>0) return $prefix4.$fname;
		$n = @ftp_size($conn,$prefix5.$fname);
        if ($n>0) return $prefix5.$fname;
        $n = @ftp_size($conn,$prefix6.$fname);
        if ($n>0) return $prefix6.$fname;
        
        return 0;
    }
    public function uploadArchive($interactive=true)
    {
		if ((!$interactive) && ($this->is_processed>=10)) return;
		$year = date('Y');
		$newdone = "DONE$year";
		$prefix1 = "/home/pbxbill/CDR/$newdone/";
		if (!is_dir($prefix1)) mkdir($prefix1);
		$prefixSvr = "/a2pdata/pbxbill/CDR/DONE$year/";
        $localLoc = '/home/pbxbill/CDR/AUTOPROCESS/';
		$conn = CdrStatus::connectFtp();
		$directories = @ftp_nlist($conn,"/a2pdata/pbxbill/CDR");
		if (!in_array($newdone,$directories))
		   @ftp_mkdir($conn,$prefixSvr);
        $fname = 'HKVCDR.'.$this->id;
        $fullname = $localLoc.$fname;
        $localsize = 0;
        $localsize = @filesize($fullname);
        $remotesize = 0;
        $remotesize = @ftp_size($conn,$prefixSvr.$fname);
		$doUpload = false;
        if (($localsize>0) && ($remotesize<=0)) $doUpload=true;
        if (($localsize>0) && ($remotesize<$localsize)) $doUpload=true;
        if ($doUpload)
        {
			if ($remotesize>0) ftp_delete($conn,$prefixSvr.$fname);
            $res = ftp_put($conn,$prefixSvr.$fname,$fullname,FTP_BINARY);
            if (!$res) throw new CHttpException(500,"Unable to upload file to ftp server");
        }
        $remotesize = @ftp_size($conn,$prefixSvr.$fname);
        if ($remotesize == $localsize)
        {
			$out = "";
        	exec("pbzip2 ".$fullname,$out);
			$out = var_export($out,true);
			if ($interactive) echo "<br>pbzip2 result is <pre>".$out."</pre><br>";
		}
		$isOk=false;
		if (file_exists($fullname.".bz2") && (@filesize($fullname.".bz2")>0))
		{
        	exec("mv ".$fullname.".bz2 ".$prefix1);
			$this->is_processed = 10+$this->is_processed;
			$this->save();
			$isOk=true;
        }
        if (!$isOk) if ($interactive) throw new CHttpException(500, "Unable to do archiving: localsize ".$localsize." remote size ".$remotesize);
    }
	/**
	 * Returns the static model of the specified AR class.
	 * @return CdrStatus the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'cdrstatus';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id', 'required'),
			array('id, is_processed, process_cnt', 'numerical', 'integerOnly'=>true),
			array('process_time', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, is_processed, process_time, process_cnt', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'is_processed' => 'Is Processed',
			'process_time' => 'Process Time',
			'process_cnt' => 'Process Cnt',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);

		$criteria->compare('is_processed',$this->is_processed);

		$criteria->compare('process_time',$this->process_time,true);

		$criteria->compare('process_cnt',$this->process_cnt);

		return new CActiveDataProvider('CdrStatus', array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/CdrStatusController.php
<?php

class CdrStatusController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','archive','archive2','update','create','batchArchive','batchArchive2','admin2'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new CdrStatus;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['CdrStatus']))
		{
			$model->attributes=$_POST['CdrStatus'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['CdrStatus']))
		{
			$model->attributes=$_POST['CdrStatus'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

    public function actionBatchArchive($fromId = 0,$toId = 0)
    {
		if (isset($_POST['fromId']))
		{
			$fromId = $_POST['fromId'];
			$toId = $_POST['toId'];
		}
		if ($fromId==0)
		{
			$c = new CDbCriteria();
			$c->compare('is_processed',11);
			$c->order = 'id desc';
			$lastArchived = CdrStatus::model()->find($c);
			$lastArchivedId = $lastArchived->id;
			$c2 = new CDbCriteria();
			$c2->compare('is_processed',1);
			$c2->compare('id', '>'.$lastArchivedId);
			$c2->order = 'id';
			$firstProcessed = CdrStatus::model()->find($c2);
			$c3 = new CDbCriteria();
			$c3->compare('is_processed',1);
			$c3->compare('id', '>'.$lastArchivedId);
			$c3->order = 'id desc';
			$lastProcessed = CdrStatus::model()->find($c3);
			$this->render('batchArchive', array('lastArchived'=>$lastArchived,'firstProcessed' =>
			$firstProcessed , 'lastProcessed' => $lastProcessed));
		} else {
			set_time_limit(0);
			CdrStatus::batchArchive($fromId,$toId);
			echo "DONE";
		}
	}
	public function actionBatchArchive2($fromId = 0,$toId = 0)
    {
		if (isset($_POST['fromId']))
		{
			$fromId = $_POST['fromId'];
			$toId = $_POST['toId'];
		}
		if ($fromId==0)
		{
			$c = new CDbCriteria();
			$c->compare('is_processed',11);
			$c->order = 'id desc';
			$lastArchived = CdrStatus2::model()->find($c);
			$lastArchivedId = $lastArchived->id;
			$c2 = new CDbCriteria();
			$c2->compare('is_processed',1);
			$c2->compare('id', '>'.$lastArchivedId);
			$c2->order = 'id';
			$firstProcessed = CdrStatus2::model()->find($c2);
			$c3 = new CDbCriteria();
			$c3->compare('is_processed',1);
			$c3->compare('id', '>'.$lastArchivedId);
			$c3->order = 'id desc';
			$lastProcessed = CdrStatus2::model()->find($c3);
			$this->render('batchArchive', array('lastArchived'=>$lastArchived,'firstProcessed' =>
			$firstProcessed , 'lastProcessed' => $lastProcessed));
		} else {
			set_time_limit(0);
			CdrStatus2::batchArchive($fromId,$toId);
			echo "DONE";
		}
    }
    public function actionArchive($id)
    {
        $model=$this->loadModel($id);
        $model->uploadArchive();
        $this->redirect(array('view','id'=>$model->id));
	}
	public function actionArchive2($id)
    {
        $model=$this->loadModel2($id);
		$model->uploadArchive();
		echo "<hr>--end of process--";
		exit;
        //$this->redirect(array('view','id'=>$model->id));
    }
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('CdrStatus');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new CdrStatus('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['CdrStatus']))
			$model->attributes=$_GET['CdrStatus'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	public function actionAdmin2()
	{
		$model=new CdrStatus2('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['CdrStatus2']))
			$model->attributes=$_GET['CdrStatus2'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return CdrStatus the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=CdrStatus::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	public function loadModel2($id)
	{
		$model=CdrStatus2::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested data does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CdrStatus $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='cdr-status-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/cdrStatus/_form.php
<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'cdr-status-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
		<?php echo $form->error($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'is_processed'); ?>
		<?php echo $form->textField($model,'is_processed'); ?>
		<?php echo $form->error($model,'is_processed'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'process_time'); ?>
		<?php echo $form->textField($model,'process_time'); ?>
		<?php echo $form->error($model,'process_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'process_cnt'); ?>
		<?php echo $form->textField($model,'process_cnt'); ?>
		<?php echo $form->error($model,'process_cnt'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/cdrStatus/_search.php
<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'is_processed'); ?>
		<?php echo $form->textField($model,'is_processed'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'process_time'); ?>
		<?php echo $form->textField($model,'process_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'process_cnt'); ?>
		<?php echo $form->textField($model,'process_cnt'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/cdrStatus/_view.php
<?php
/* @var $this CdrStatusController */
/* @var $data CdrStatus */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('is_processed')); ?>:</b>
	<?php echo CHtml::encode($data->is_processed); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('process_time')); ?>:</b>
	<?php echo CHtml::encode($data->process_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('process_cnt')); ?>:</b>
	<?php echo CHtml::encode($data->process_cnt); ?>
	<br />
    <b><?php echo CHtml::encode($data->getAttributeLabel('archive_size')); ?>:</b>
	<?php echo CHtml::encode($data->archiveSize); ?>
	<br />


</div>

protected/views/cdrStatus/admin.php
<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */

$this->breadcrumbs=array(
	'Cdr Statuses'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List CdrStatus', 'url'=>array('index')),
	array('label'=>'Create CdrStatus', 'url'=>array('create')),
	array('label'=>'Batch Archive CdrStatus', 'url'=>array('batchArchive')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#cdr-status-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Cdr Statuses</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'cdr-status-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'is_processed',
		'process_time',
		'process_cnt',
        'archiveSize',
        'archiveName',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/cdrStatus/batchArchive.php
<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */

$this->breadcrumbs=array(
	'Cdr Statuses'=>array('index'),
	'Batch Archive',
);

$this->menu=array(
	array('label'=>'List CdrStatus', 'url'=>array('index')),
    array('label'=>'Manage CdrStatus', 'url'=>array('admin')),
    array('label'=>'Batch Archive CdrStatus', 'url'=>array('batchArchive')),
);
?>

<h1>Batch Archive CdrStatus</h1>

<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'cdr-status-form',
	'enableAjaxValidation'=>false,
)); ?>

	<div class="row">
		<?php echo CHtml::textField('fromId',$firstProcessed->id); ?>
	</div>

	<div class="row">
        <?php echo CHtml::textField('toId',$lastProcessed->id); ?>
	</div>


	<div class="row buttons">
		<?php echo CHtml::submitButton('Archive'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/cdrStatus/create.php
<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */

$this->breadcrumbs=array(
	'Cdr Statuses'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List CdrStatus', 'url'=>array('index')),
	array('label'=>'Manage CdrStatus', 'url'=>array('admin')),
);
?>

<h1>Create CdrStatus</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/cdrStatus/index.php
<?php
/* @var $this CdrStatusController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Cdr Statuses',
);

$this->menu=array(
	array('label'=>'Create CdrStatus', 'url'=>array('create')),
	array('label'=>'Manage CdrStatus', 'url'=>array('admin')),
);
?>

<h1>Cdr Statuses</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/cdrStatus/update.php
<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */

$this->breadcrumbs=array(
	'Cdr Statuses'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List CdrStatus', 'url'=>array('index')),
	array('label'=>'Create CdrStatus', 'url'=>array('create')),
	array('label'=>'View CdrStatus', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage CdrStatus', 'url'=>array('admin')),
);
?>

<h1>Update CdrStatus <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/cdrStatus/view.php
<?php
/* @var $this CdrStatusController */
/* @var $model CdrStatus */

$this->breadcrumbs=array(
	'Cdr Statuses'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List CdrStatus', 'url'=>array('index')),
	array('label'=>'Create CdrStatus', 'url'=>array('create')),
	array('label'=>'Update CdrStatus', 'url'=>array('update', 'id'=>$model->id)),
	//array('label'=>'Delete CdrStatus', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
    array('label'=>'Archive Cdr File', 'url'=>array('archive', 'id'=>$model->id)),
	array('label'=>'Manage CdrStatus', 'url'=>array('admin')),
);
?>

<h1>View CdrStatus #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'is_processed',
		'process_time',
		'process_cnt',
        'archiveSize',
        'archiveName',
	),
)); ?>